import type { Menu } from './types';

export const menuData: Menu = [
  {
    name: 'Pizzas',
    icon: 'Pizza',
    items: [
      {
        id: 'pizza-1',
        name: 'Margherita',
        description: 'Classic tomato, mozzarella, and basil.',
        price: 12.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Tomato Sauce', 'Mozzarella', 'Fresh Basil', 'Olive Oil'],
        aiHint: 'margherita pizza',
      },
      {
        id: 'pizza-2',
        name: 'Pepperoni',
        description: 'Spicy pepperoni with a rich tomato sauce.',
        price: 14.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Tomato Sauce', 'Mozzarella', 'Pepperoni'],
        aiHint: 'pepperoni pizza',
      },
      {
        id: 'pizza-3',
        name: 'Veggie Supreme',
        description: 'A garden of fresh vegetables on a pizza.',
        price: 15.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Tomato Sauce', 'Mozzarella', 'Bell Peppers', 'Onions', 'Olives', 'Mushrooms'],
        aiHint: 'veggie pizza',
      },
      {
        id: 'pizza-4',
        name: 'BBQ Chicken',
        description: 'Tangy BBQ sauce, chicken, and red onions.',
        price: 16.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['BBQ Sauce', 'Mozzarella', 'Grilled Chicken', 'Red Onions', 'Cilantro'],
        aiHint: 'bbq chicken',
      },
    ],
  },
  {
    name: 'Sides',
    icon: 'Utensils',
    items: [
      {
        id: 'side-1',
        name: 'Garlic Bread',
        description: 'Toasted bread with garlic, butter, and herbs.',
        price: 5.99,
        image: 'https://picsum.photos/600/400',
        category: 'Sides',
        aiHint: 'garlic bread',
      },
      {
        id: 'side-2',
        name: 'Chicken Wings',
        description: 'Spicy and savory chicken wings.',
        price: 8.99,
        image: 'https://picsum.photos/600/400',
        category: 'Sides',
        aiHint: 'chicken wings',
      },
      {
        id: 'side-3',
        name: 'French Fries',
        description: 'Crispy golden french fries.',
        price: 4.50,
        image: 'https://picsum.photos/600/400',
        category: 'Sides',
        aiHint: 'french fries',
      },
    ],
  },
    {
    name: 'Burgers',
    icon: 'Beef',
    items: [
      {
        id: 'burger-1',
        name: 'Classic Cheeseburger',
        description: 'Beef patty, cheese, lettuce, tomato, and our special sauce.',
        price: 10.99,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'cheeseburger',
      },
      {
        id: 'burger-2',
        name: 'Bacon Burger',
        description: 'The classic, but with crispy bacon.',
        price: 12.50,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'bacon burger',
      },
    ],
  },
  {
    name: 'Sandwiches',
    icon: 'Sandwich',
    items: [
      {
        id: 'sandwich-1',
        name: 'Club Sandwich',
        description: 'Turkey, bacon, lettuce, tomato, and mayo.',
        price: 9.99,
        image: 'https://picsum.photos/600/400',
        category: 'Sandwiches',
        aiHint: 'club sandwich',
      },
       {
        id: 'sandwich-2',
        name: 'Italian Sub',
        description: 'Salami, ham, provolone, and veggies.',
        price: 10.50,
        image: 'https://picsum.photos/600/400',
        category: 'Sandwiches',
        aiHint: 'italian sub',
      },
    ],
  },
  {
    name: 'Shakes',
    icon: 'GlassWater',
    items: [
      {
        id: 'shake-1',
        name: 'Chocolate Shake',
        description: 'Rich and creamy chocolate milkshake.',
        price: 6.50,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes',
        aiHint: 'chocolate milkshake',
      },
      {
        id: 'shake-2',
        name: 'Vanilla Shake',
        description: 'Classic vanilla milkshake.',
        price: 6.50,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes',
        aiHint: 'vanilla milkshake',
      },
      {
        id: 'shake-3',
        name: 'Strawberry Shake',
        description: 'Sweet strawberry milkshake.',
        price: 6.50,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes',
        aiHint: 'strawberry milkshake',
      },
    ],
  },
  {
    name: 'Breads',
    icon: 'CakeSlice',
    items: [
      {
        id: 'bread-1',
        name: 'Garlic Knots',
        description: 'Soft and chewy garlic knots with dipping sauce.',
        price: 6.99,
        image: 'https://picsum.photos/600/400',
        category: 'Breads',
        aiHint: 'garlic knots',
      },
    ],
  },
  {
    name: 'Pasta',
    icon: 'Soup',
    items: [
      {
        id: 'pasta-1',
        name: 'Spaghetti Bolognese',
        description: 'Classic meat sauce over spaghetti.',
        price: 13.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pasta',
        aiHint: 'spaghetti bolognese',
      },
       {
        id: 'pasta-2',
        name: 'Fettuccine Alfredo',
        description: 'Creamy alfredo sauce over fettuccine.',
        price: 14.50,
        image: 'https://picsum.photos/600/400',
        category: 'Pasta',
        aiHint: 'fettuccine alfredo',
      },
    ],
  },
];
