import type { Menu } from './types';

export const menuData: Menu = [
  {
    name: 'Pizzas',
    icon: 'Pizza',
    items: [
      {
        id: 'pizza-1',
        name: 'Pepperoni Classic',
        description: 'Tomato sauce, mozzarella, and premium pepperoni.',
        price: 12.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Mushrooms', 'Olives', 'Extra Cheese'],
        aiHint: 'pepperoni pizza',
      },
      {
        id: 'pizza-2',
        name: 'Margherita',
        description: 'Fresh tomatoes, basil, and creamy mozzarella.',
        price: 10.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Cherry Tomatoes', 'Basil', 'Extra Cheese'],
        aiHint: 'margherita pizza',
      },
      {
        id: 'pizza-3',
        name: 'BBQ Chicken',
        description: 'Smoky BBQ sauce, grilled chicken, and red onions.',
        price: 13.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Jalapenos', 'Sweet Corn', 'Bacon'],
        aiHint: 'bbq chicken pizza',
      },
      {
        id: 'pizza-4',
        name: 'Veggie Supreme',
        description: 'Peppers, olives, mushrooms, onions, sweet corn.',
        price: 11.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Spinach', 'Cherry Tomatoes', 'Extra Cheese'],
        aiHint: 'veggie pizza',
      },
      {
        id: 'pizza-5',
        name: 'Meat Lovers',
        description: 'Pepperoni, sausage, ham, bacon, mozzarella.',
        price: 14.99,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Extra Meat', 'Onions', 'Extra Cheese'],
        aiHint: 'meat lovers pizza',
      },
      {
        id: 'pizza-6',
        name: 'Hawaiian',
        description: 'Ham, pineapple, mozzarella, and tomato base.',
        price: 12.49,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Jalapenos', 'Bacon', 'Extra Cheese'],
        aiHint: 'hawaiian pizza',
      },
    ],
  },
];
