import type { Menu } from './types';

export const menuData: Menu = [
  {
    name: 'Pizzas',
    icon: 'Pizza',
    items: [
      {
        id: 'pizza-1',
        name: 'Margherita',
        description: 'Single Cheese Topping',
        price: 100,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Cheese', 'Tomato'],
        aiHint: 'margherita pizza',
      },
      {
        id: 'pizza-2',
        name: 'Spicy Tango Pizza',
        description: 'Golden Corn, Jalapeno & Red Paprika',
        price: 130,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Golden Corn', 'Jalapeno', 'Red Paprika'],
        aiHint: 'spicy pizza',
      },
      {
        id: 'pizza-3',
        name: 'Double Cheese Margherita',
        description: 'Loaded with Extra Cheese',
        price: 130,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Extra Cheese'],
        aiHint: 'cheese pizza',
      },
      {
        id: 'pizza-4',
        name: 'Farmfresh',
        description: 'Onion, Capsicum, Tomato & Mushroom',
        price: 150,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Onion', 'Capsicum', 'Tomato', 'Mushroom'],
        aiHint: 'farm fresh',
      },
      {
        id: 'pizza-5',
        name: 'Country Feast',
        description: 'Onion, Capsicum & Tomato',
        price: 150,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Onion', 'Capsicum', 'Tomato'],
        aiHint: 'country pizza',
      },
      {
        id: 'pizza-6',
        name: 'Maxican Green Pizza',
        description: 'Onion, Capsicum, Tomato & Jalapeno',
        price: 150,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Onion', 'Capsicum', 'Tomato', 'Jalapeno'],
        aiHint: 'mexican pizza',
      },
      {
        id: 'pizza-7',
        name: 'Peppy Paneer',
        description: 'Onion, Red Paprika, Capsicum & Paneer',
        price: 170,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Onion', 'Red Paprika', 'Capsicum', 'Paneer'],
        aiHint: 'paneer pizza',
      },
      {
        id: 'pizza-8',
        name: 'Deluxe Veggie',
        description: 'Onion, Capsicum, Paneer, Golden Corn & Mushroom',
        price: 170,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Onion', 'Capsicum', 'Paneer', 'Golden Corn', 'Mushroom'],
        aiHint: 'veggie pizza',
      },
      {
        id: 'pizza-9',
        name: 'Tandoori Paneer Pizza',
        description: 'Onion, Red Peprika, Smokey Paneer, Capsicum, Jalapeno',
        price: 170,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Onion', 'Red Peprika', 'Smokey Paneer', 'Capsicum', 'Jalapeno'],
        aiHint: 'tandoori pizza',
      },
      {
        id: 'pizza-10',
        name: 'Chef\'s Veg Special',
        description: 'Red Peprika, Capcisum, Mushroom, Jalapeno, Paneer & Golden Corn',
        price: 200,
        image: 'https://picsum.photos/600/400',
        category: 'Pizzas',
        ingredients: ['Red Peprika', 'Capsicum', 'Mushroom', 'Jalapeno', 'Paneer', 'Golden Corn'],
        aiHint: 'chef special',
      },
    ],
  },
  {
    name: 'Sandwiches',
    icon: 'Sandwich',
    items: [
      {
        id: 'sandwich-1',
        name: 'Veg Sandwich',
        description: 'A classic grilled vegetable sandwich.',
        price: 70,
        image: 'https://picsum.photos/600/400',
        category: 'Sandwiches',
        aiHint: 'veg sandwich',
      },
      {
        id: 'sandwich-2',
        name: 'Paneer Sandwich',
        description: 'Grilled sandwich with a savory paneer filling.',
        price: 90,
        image: 'https://picsum.photos/600/400',
        category: 'Sandwiches',
        aiHint: 'paneer sandwich',
      },
      {
        id: 'sandwich-3',
        name: 'Tikka Paneer Sandwich',
        description: 'Grilled sandwich with spicy tikka paneer.',
        price: 110,
        image: 'https://picsum.photos/600/400',
        category: 'Sandwiches',
        aiHint: 'tikka sandwich',
      },
      {
        id: 'sandwich-4',
        name: 'Achari Paneer Sandwich',
        description: 'Grilled sandwich with pickle-flavored paneer.',
        price: 120,
        image: 'https://picsum.photos/600/400',
        category: 'Sandwiches',
        aiHint: 'achari sandwich',
      },
    ],
  },
  {
    name: 'Burgers',
    icon: 'Beef',
    items: [
      {
        id: 'burger-1',
        name: 'Potato Crisp Burger',
        description: 'A unique burger with a crispy potato patty.',
        price: 40,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'potato burger',
      },
      {
        id: 'burger-2',
        name: 'Tandoori Burger',
        description: 'Burger with a tandoori-flavored patty.',
        price: 45,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'tandoori burger',
      },
      {
        id: 'burger-3',
        name: 'Chunky Cheese Burger',
        description: 'A burger packed with chunky cheese.',
        price: 50,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'cheese burger',
      },
      {
        id: 'burger-4',
        name: 'Chipotley Burger',
        description: 'A smoky and spicy chipotle burger.',
        price: 60,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'chipotle burger',
      },
      {
        id: 'burger-5',
        name: 'Tandoori Paneer Burger',
        description: 'Burger with a tandoori paneer patty.',
        price: 60,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'paneer burger',
      },
      {
        id: 'burger-6',
        name: 'Aachari tadka Paneer Burger',
        description: 'Burger with a pickle-flavored paneer patty.',
        price: 80,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'achari burger',
      },
      {
        id: 'burger-7',
        name: 'Paneer Patty Burger',
        description: 'A delicious paneer patty burger.',
        price: 100,
        image: 'https://picsum.photos/600/400',
        category: 'Burgers',
        aiHint: 'paneer patty',
      },
    ],
  },
  {
    name: 'Sides',
    icon: 'Utensils',
    items: [
      {
        id: 'side-1',
        name: 'French Fries',
        description: 'Classic crispy french fries.',
        price: 70,
        image: 'https://picsum.photos/600/400',
        category: 'Sides',
        aiHint: 'french fries',
      },
      {
        id: 'side-2',
        name: 'Peri Peri Masala Fries',
        description: 'Fries tossed in spicy peri peri masala.',
        price: 80,
        image: 'https://picsum.photos/600/400',
        category: 'Sides',
        aiHint: 'masala fries',
      },
       {
        id: 'side-3',
        name: 'Zingy Parcel',
        description: 'A crispy parcel with a zingy filling.',
        price: 50,
        image: 'https://picsum.photos/600/400',
        category: 'Sides',
        aiHint: 'zingy parcel',
      },
      {
        id: 'side-4',
        name: 'Cheese Dip',
        description: 'A creamy and delicious cheese dip.',
        price: 25,
        image: 'https://picsum.photos/600/400',
        category: 'Sides',
        aiHint: 'cheese dip',
      },
    ],
  },
  {
    name: 'Shakes & Mocktails',
    icon: 'GlassWater',
    items: [
      {
        id: 'shake-1',
        name: 'Strawberry Shakes',
        description: 'A refreshing strawberry shake.',
        price: 70,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes & Mocktails',
        aiHint: 'strawberry shake',
      },
      {
        id: 'shake-2',
        name: 'Mango Shakes',
        description: 'A sweet and creamy mango shake.',
        price: 70,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes & Mocktails',
        aiHint: 'mango shake',
      },
      {
        id: 'shake-3',
        name: 'Chocolate Shakes',
        description: 'A rich and decadent chocolate shake.',
        price: 80,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes & Mocktails',
        aiHint: 'chocolate shake',
      },
      {
        id: 'shake-4',
        name: 'Cold Coffee',
        description: 'A classic cold coffee.',
        price: 80,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes & Mocktails',
        aiHint: 'cold coffee',
      },
      {
        id: 'shake-5',
        name: 'Mint Mojito',
        description: 'A refreshing mint mojito.',
        price: 60,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes & Mocktails',
        aiHint: 'mint mojito',
      },
      {
        id: 'shake-6',
        name: 'Water Melon',
        description: 'Cool and refreshing water melon juice.',
        price: 60,
        image: 'https://picsum.photos/600/400',
        category: 'Shakes & Mocktails',
        aiHint: 'watermelon juice',
      },
    ],
  },
  {
    name: 'Breads',
    icon: 'CakeSlice',
    items: [
      {
        id: 'bread-1',
        name: 'Garlic Bread',
        description: 'Classic garlic bread.',
        price: 90,
        image: 'https://picsum.photos/600/400',
        category: 'Breads',
        aiHint: 'garlic bread',
      },
      {
        id: 'bread-2',
        name: 'Stuffed Garlic Bread',
        description: 'Garlic bread stuffed with delicious fillings.',
        price: 110,
        image: 'https://picsum.photos/600/400',
        category: 'Breads',
        aiHint: 'stuffed garlic',
      },
      {
        id: 'bread-3',
        name: 'Paneer Stuffed Garlic Bread',
        description: 'Garlic bread stuffed with paneer.',
        price: 150,
        image: 'https://picsum.photos/600/400',
        category: 'Breads',
        aiHint: 'paneer garlic',
      },
      {
        id: 'bread-4',
        name: 'Veg Calzon Pocket',
        description: 'A delicious vegetable calzone pocket.',
        price: 130,
        image: 'https://picsum.photos/600/400',
        category: 'Breads',
        aiHint: 'calzone pocket',
      },
    ],
  },
  {
    name: 'Pasta',
    icon: 'Soup',
    items: [
      {
        id: 'pasta-1',
        name: 'White Sauce Pasta',
        description: 'Pasta in a creamy white sauce.',
        price: 120,
        image: 'https://picsum.photos/600/400',
        category: 'Pasta',
        aiHint: 'white pasta',
      },
      {
        id: 'pasta-2',
        name: 'Red Sauce Pasta',
        description: 'Pasta in a tangy red sauce.',
        price: 120,
        image: 'https://picsum.photos/600/400',
        category: 'Pasta',
        aiHint: 'red pasta',
      },
      {
        id: 'pasta-3',
        name: 'Mix Sauce Pasta',
        description: 'A mix of white and red sauce pasta.',
        price: 120,
        image: 'https://picsum.photos/600/400',
        category: 'Pasta',
        aiHint: 'mix pasta',
      },
    ],
  },
  {
    name: 'Desserts',
    icon: 'Cake',
    items: [
      {
        id: 'dessert-1',
        name: 'Chocolava Cake',
        description: 'A decadent chocolate lava cake.',
        price: 60,
        image: 'https://picsum.photos/600/400',
        category: 'Desserts',
        aiHint: 'lava cake',
      },
    ],
  },
];
